Repository tiramisugithub/AI_verification, pull requests merged in 2024-09, with the labels that each got.

#54 Feat/review
  build.gradle
  src/main/java/com/sparta/aiverification/Timestamped.java
  src/main/java/com/sparta/aiverification/config/QuerydslConfig.java
  src/main/java/com/sparta/aiverification/order/service/OrderService.java
  src/main/java/com/sparta/aiverification/review/controller/ReviewController.java
  src/main/java/com/sparta/aiverification/review/dto/ReviewErrorCode.java
  src/main/java/com/sparta/aiverification/review/dto/ReviewRequestDto.java
  src/main/java/com/sparta/aiverification/review/dto/ReviewResponseDto.java
  src/main/java/com/sparta/aiverification/review/entity/Review.java
  src/main/java/com/sparta/aiverification/review/repository/ReviewRepository.java
  src/main/java/com/sparta/aiverification/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/sparta/aiverification/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/sparta/aiverification/review/service/ReviewService.java
Labels: enhancement

#57 Fix : ai-api 적용
  src/main/java/com/sparta/aiverification/ai/repository/AIRepository.java
  src/main/java/com/sparta/aiverification/ai/service/AIService.java
  src/main/java/com/sparta/aiverification/config/AppConfig.java
  src/main/java/com/sparta/aiverification/menu/controller/MenuController.java
  src/main/java/com/sparta/aiverification/menu/service/MenuService.java
Labels: enhancement

#56 Feat/store menu search
  build.gradle
  src/main/java/com/sparta/aiverification/common/UserAuditorAware.java
  src/main/java/com/sparta/aiverification/menu/controller/MenuController.java
  src/main/java/com/sparta/aiverification/menu/repository/MenuRepository.java
  src/main/java/com/sparta/aiverification/menu/repository/MenuRepositoryCustom.java
  src/main/java/com/sparta/aiverification/menu/repository/MenuRepositoryImpl.java
  src/main/java/com/sparta/aiverification/menu/service/MenuService.java
  src/main/java/com/sparta/aiverification/order/controller/OrderController.java
  src/main/java/com/sparta/aiverification/order/service/OrderService.java
  src/main/java/com/sparta/aiverification/store/controller/StoreController.java
  src/main/java/com/sparta/aiverification/store/repository/StoreRepository.java
  src/main/java/com/sparta/aiverification/store/repository/StoreRepositoryCustom.java
  src/main/java/com/sparta/aiverification/store/repository/StoreRepositoryImpl.java
  src/main/java/com/sparta/aiverification/store/service/StoreService.java
  src/main/java/com/sparta/aiverification/user/service/UserService.java
Labels: bug, enhancement

#59 Feat : User 삭제 기능 수정, 소프트 삭제 적용
  src/main/java/com/sparta/aiverification/user/controller/AdminController.java
  src/main/java/com/sparta/aiverification/user/controller/UserController.java
  src/main/java/com/sparta/aiverification/user/entity/User.java
  src/main/java/com/sparta/aiverification/user/service/AdminService.java
  src/main/java/com/sparta/aiverification/user/service/UserService.java
Labels: enhancement

#62 Feat : User ErrorCode 수정
  src/main/java/com/sparta/aiverification/user/dto/UserErrorCode.java
  src/main/java/com/sparta/aiverification/user/service/AdminService.java
  src/main/java/com/sparta/aiverification/user/service/UserService.java
Labels: enhancement

#64 Feat : 가게 목록을 조회시 평점을 노출 하도록 수정
  src/main/java/com/sparta/aiverification/order/controller/OrderController.java
  src/main/java/com/sparta/aiverification/payment/service/PaymentService.java
  src/main/java/com/sparta/aiverification/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/sparta/aiverification/store/controller/StoreController.java
  src/main/java/com/sparta/aiverification/store/dto/StoreResponseDto.java
  src/main/java/com/sparta/aiverification/store/repository/StoreRepositoryCustom.java
  src/main/java/com/sparta/aiverification/store/repository/StoreRepositoryImpl.java
  src/main/java/com/sparta/aiverification/store/service/StoreService.java
Labels: enhancement

#66 Feat : 잘못 queryDsl 수정
  src/main/java/com/sparta/aiverification/payment/repository/PaymentRepositoryImpl.java
  src/main/java/com/sparta/aiverification/review/repository/ReviewRepositoryImpl.java
Labels: bug

#70 Dev
  src/main/java/com/sparta/aiverification/menu/controller/MenuController.java
  src/main/java/com/sparta/aiverification/menu/service/MenuService.java
  src/main/java/com/sparta/aiverification/payment/repository/PaymentRepositoryImpl.java
  src/main/java/com/sparta/aiverification/review/repository/ReviewRepositoryImpl.java
Labels: bug
